name: get_files
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
      info:
        description: "提取文件信息"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          device1=$(echo ${{ github.event.inputs.URL }} | cut -d"_" -f2)
          echo "device=$(echo ${device1,,})" >> $GITHUB_ENV
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd dos2unix
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
          mkdir -p "$GITHUB_WORKSPACE"/get_files
          sudo chmod -R 777 "$GITHUB_WORKSPACE"/tools
      - name: 2.下载系统包
        run: |
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
      - name: 3.检测payload/br
        run: |
          ZIP_NAME=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f5)
          7z x "$GITHUB_WORKSPACE"/$ZIP_NAME -r -o"$GITHUB_WORKSPACE"/${{ env.device }} && rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME
          if [[ -e "$GITHUB_WORKSPACE"/${{ env.device }}/payload.bin ]]; then
              echo "unpack=payload" >> $GITHUB_ENV
          else
              echo "unpack=br" >> $GITHUB_ENV
          fi
      - if: ${{ env.unpack == 'payload' }}
        name: 4.解压payload
        run: |
          unpack_partiton="product"
          # unpack_partiton="system odm system_ext product vendor mi_ext"
          for i in $unpack_partiton; do
              "$GITHUB_WORKSPACE"/tools/payload-dumper-go -o "$GITHUB_WORKSPACE"/${{ env.device }}/ -p $i "$GITHUB_WORKSPACE"/${{ env.device }}/payload.bin > /dev/null
              if [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img) == "ext" ]]; then
                  sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux/imgextractorLinux.py "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img "$GITHUB_WORKSPACE"/${{ env.device }} > /dev/null
              elif [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img) == "erofs" ]]; then
                  cd "$GITHUB_WORKSPACE"/${{ env.device }} && "$GITHUB_WORKSPACE"/tools/extract.erofs -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img -x > /dev/null && cd "$GITHUB_WORKSPACE"
              fi
              rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img
          done
          sudo rm -rf  "$GITHUB_WORKSPACE"/${{ env.device }}/config "$GITHUB_WORKSPACE"/${{ env.device }}/TI_config "$GITHUB_WORKSPACE"/${{ env.device }}/payload.bin
      - if: ${{ env.unpack == 'br' }}
        name: 4.解压br
        run: |
          unpack_partiton="product"
          # unpack_partiton="system odm system_ext product vendor mi_ext"
          for i in $unpack_partiton; do
            "$GITHUB_WORKSPACE"/tools/brotli -d "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat.br > /dev/null
            rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat.br
            python3 "$GITHUB_WORKSPACE"/tools/sdat2img.py "$GITHUB_WORKSPACE"/${{ env.device }}/$i.transfer.list "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img > /dev/null
            rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.patch.dat "$GITHUB_WORKSPACE"/${{ env.device }}/$i.transfer.list "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat
            if [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img) == "ext" ]]; then
              sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux/imgextractorLinux.py "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img "$GITHUB_WORKSPACE"/${{ env.device }} > /dev/null
            elif [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img) == "erofs" ]]; then
              cd "$GITHUB_WORKSPACE"/${{ env.device }} && "$GITHUB_WORKSPACE"/tools/extract.erofs -i "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img -x > /dev/null && cd "$GITHUB_WORKSPACE"
            fi
            rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img
          done
          sudo rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/TI_config "$GITHUB_WORKSPACE"/${{ env.device }}/config
      - name: 5.提取指定文件
        run: |
          get_prop_files(){
            # mi_ext_build_prop=$(sudo find "$GITHUB_WORKSPACE"/"$device"/mi_ext -name "build.prop")
            # sudo cp -f "$GITHUB_WORKSPACE"/"$device"/system/system/build.prop "$GITHUB_WORKSPACE"/get_files/system
            # sudo cp -f "$GITHUB_WORKSPACE"/"$device"/vendor/build.prop "$GITHUB_WORKSPACE"/get_files/vendor
            # sudo cp -f "$GITHUB_WORKSPACE"/"$device"/system_ext/etc/build.prop "$GITHUB_WORKSPACE"/get_files/system_ext
            # sudo cp -f "$GITHUB_WORKSPACE"/"$device"/odm/etc/build.prop "$GITHUB_WORKSPACE"/get_files/odm
            sudo cp -f "$GITHUB_WORKSPACE"/"$device"/product/etc/build.prop "$GITHUB_WORKSPACE"/get_files/product
            sudo 7z a "$GITHUB_WORKSPACE"/get_files/devicefeatures.zip "$GITHUB_WORKSPACE"/"$device"/product/etc/device_features/*
            sudo 7z a "$GITHUB_WORKSPACE"/get_files/overlay.zip "$GITHUB_WORKSPACE"/"$device"/product/overlay/*
            sudo 7z a "$GITHUB_WORKSPACE"/get_files/MiuiCamera.zip "$GITHUB_WORKSPACE"/"$device"/product/priv-app/MiuiCamera/*
            # sudo cp -f "$mi_ext_build_prop" "$GITHUB_WORKSPACE"/get_files/mi_ext
          }
          # mkdir -p "$GITHUB_WORKSPACE"/get_files/system
          # mkdir -p "$GITHUB_WORKSPACE"/get_files/vendor
          # mkdir -p "$GITHUB_WORKSPACE"/get_files/system_ext
          mkdir -p "$GITHUB_WORKSPACE"/get_files/product
          # mkdir -p "$GITHUB_WORKSPACE"/get_files/odm
          # mkdir -p "$GITHUB_WORKSPACE"/get_files/mi_ext
          get_prop_files
        env:
          device: ${{ env.device }}
      - name: 6.查询提取次数
        id: get-cache
        uses: actions/cache@main
        with:
          path: |
            ${{ env.device }}_count
          key: ${{ env.device }}
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        name: 7.生成提取次数
        run: |
          touch $GITHUB_WORKSPACE/${{ env.device }}_count
          echo 1 > $GITHUB_WORKSPACE/${{ env.device }}_count
          echo "number=1"  >> $GITHUB_ENV
      - name: 8.打包
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/zip
          sudo chmod -R 777 "$GITHUB_WORKSPACE"/get_files
          7z a "$GITHUB_WORKSPACE"/zip/"$device"_get_files.zip "$GITHUB_WORKSPACE"/get_files/*
          number=$(cat $GITHUB_WORKSPACE/"$device"_count)
          if [[ $number != 1 ]]; then
              ((number++))
              echo $number >$GITHUB_WORKSPACE/"$device"_count
              echo "number=$number"  >> $GITHUB_ENV
          fi
          mv "$GITHUB_WORKSPACE"/zip/"$device"_get_files.zip "$GITHUB_WORKSPACE"/zip/"$device"_"${{ env.date }}"_"$number".zip
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo "${{ github.event.inputs.info }}" > file.log
        env:
          device: ${{ env.device }}
      - name: 9.上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/zip/*
          name: ${{ env.device }}
          tag: ${{ env.device }}
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 10.发送开始构建通知
        run: |
          number=$(cat $GITHUB_WORKSPACE/"$device"_count)
          if [[ "${{ env.device }}" == "umi" ]]; then
              curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"小米10 ${{ env.date }}_${{ env.number }} 已完成提取","content":" **本次提取文件为：${{ github.event.inputs.info }}** ","topic":"get_system_files","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "${{ env.device }}" == "cmi" ]]; then
              curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"小米10Pro ${{ env.date }}_${{ env.number }} 已完成提取","content":" **本次提取文件为：${{ github.event.inputs.info }}** ","topic":"get_system_files","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "${{ env.device }}" == "cas" ]]; then
              curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"小米10 Ultra ${{ env.date }}_${{ env.number }} 已完成提取","content":" **本次提取文件为：${{ github.event.inputs.info }}** ","topic":"get_system_files","template":"markdown"}' http://www.pushplus.plus/send || true
          fi
